# Generated by Django 3.2.3 on 2021-06-09 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Foodapp', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemquantity', models.IntegerField(default=1)),
                ('total', models.FloatField()),
                ('currentuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodapp.food')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
