# Generated by Django 3.2.3 on 2021-06-15 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Foodapp', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSummery1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, default='2021-06-15 08:30', max_length=25)),
                ('totalamount', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=19)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order summery',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('foodQuant', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodapp.food')),
                ('ordersobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Foodapp.ordersummery1')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
