# Generated by Django 3.2.3 on 2021-06-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodapp', '0005_orders_ordersummery1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummery1',
            name='date',
            field=models.CharField(blank=True, default='2021-06-16 09:30', max_length=25),
        ),
        migrations.AlterModelTable(
            name='ordersummery1',
            table='ordersummery',
        ),
    ]
